name: Cycle Import Check

on:
  push:
    branches:
      *

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.17 

    - name: Run go vet
      run: go vet ./...

    - name: Check for cycle in output
      run: |
        if grep -q 'cycle' <<< "$(go vet ./...)"; then
          echo "Error: go vet detected cycle in the code."
          exit 1
        fi
